<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    /**
     * Gets items with amount > 0
     */
    public function getAvailableItems()
    {
        $qb = $this->createQueryBuilder('i');
        
        $query = $qb->where('i.amount > 0')->getQuery();
        
        
        
        return $query->getResult();
    }
    
     /**
     * Gets items with amount == 0
     */
    public function getNotAvailableItems()
    {
        $qb = $this->createQueryBuilder('i');
        
        $query = $qb->where('i.amount = 0')->getQuery();
        
        return $query->getResult();
    }
    
     /**
      * Gets items with amount above or qual $amount
      * @param type $amount
      * @return type
      */
    public function getItemsWithAmountAboveOrEqual($amount)
    {
        $qb = $this->createQueryBuilder('i');
        
        $query = $qb->where('i.amount >= :amount')
                ->setParameter(':amount', $amount)
                ->getQuery();
        
        return $query->getResult();
    }
}
